[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Code for the Advent of Code 2025 competition"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
    "pulp>=3.3.0",
]
